# Site & SEO settings
title: Luis Puerto Jr.
email: luis.jr@luispuerto.net
description: >
  This the personal blog of Luis Puerto Jr. At the moment his parents are the 
  ones managing and writing on it. 
url: "https://jr.luispuerto.net"
baseurl: ""
google_analytics: UA—XXXXXXXX-X
twitter_username: 
default_img: https://picsum.photos/2000/1200?image=1003

# Profile settings

## Main Profile
name: Luis Puerto Díaz
profile_img: https://picsum.photos/2000/1200?image=1003
about: >
    I just born and I'm here. Son of Olalla & Luis. 
    True European, since I was born in Finland from 
    Spanish parents. I just born and I'm here. 
social:
  github: https://github.com/luispuerto/jr.luispuerto.net
copyright: LPD

## Additional profiles
authors: 
      
  lpuerto:
    name: Luis Puerto Sr.
    profile_img: https://luispuerto.net/assets/images/pages/header-splash.jpg
    about: >
        Father of the owner of the site. Born in Ponferrada, Spain. 
        A Forest Engineer interested in Science and Technology. 
        Fascinated about almost everything
    email: luis@luispuerto.net
    social:
      twitter: https://twitter.com/lpuerto
      linkedin: https://www.linkedin.com/in/lpuerto
      github: https://github.com/luispuerto/
      user-circle: https:luispuerto.net

  olalla:
    name: Olalla Díaz Yáñez
    profile_img: https://olalladiaz.net/assets/images/profile.jpg
    about: >
        Mother of the owner of the web. 
    social:
      twitter: http://twitter.com/olalla
      instagram: http://instagram.com/olalla
      github: https://github.com/oldiya
      user-circle: https://olalladiaz.net


# Build settings
markdown: kramdown
highlighter: rouge
incremental: false
future: false
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
include: 
  - _pages
  - _redirects
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  math_engine_opts: # more info: https://kramdown.gettalong.org/math_engine/mathjax.html
    preview: false
    preview_as_code: false 
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Outputting
paginate: 5
paginate_path: "/blog/page-:num"
permalink: /:year/:month/:day/:title/
timezone: UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Sass
sass:
  style: compressed
