# Site/SEO settings
email: junior@luispuerto.net
permalink: /:year/:month/:day/:title/
google_analytics: 

title: >
  Luis Puerto Jr.
description: 
url: "https://jr.luispuerto.net"
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: Luis Puerto Díaz
profile_img: https://picsum.photos/2000/1200?image=1003
profile: I just born and I'm here 
social:
  github: https://github.com/luispuerto/jr.luispuerto.net
copyright: LPD

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
include: 
  - _pages
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Outputting
paginate: 5
paginate_path: "/blog/page-:num"
timezone: UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Sass
sass:
  style: compressed
